=== rndmorris/Salis-Arcana/docs/research/schematic.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Research",
  "description": "A Thaumcraft research to add or modify",
  "type": "object",
  "properties": {
    "key": {
      "type": "string",
      "description": "The unique key for this research. If this key already exists, the research will be updated"
    },
    "category": {
      "type": "string",
      "description": "The category in the Thaumonomicon to place this research"
    },
    "name": {
      "type": "string",
      "description": "The localized name of this research"
    },
    "tooltip": {
      "type": "string",
      "description": "The localized tooltip of this research"
    },
    "aspects": {
      "type": "array",
      "description": "The aspects required for this research. This is used for things like purchasing the research or creating research notes.",
      "items": {
        "type": "object",
        "properties": {
          "aspect": {
            "type": "string",
            "description": "The aspect itself"
          },
          "amount": {
            "type": "integer",
            "description": "The amount of the aspect"
          }
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "parents": {
      "type": "array",
      "description": "The parent researches required for this research",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "siblings": {
      "type": "array",
      "description": "The sibling researches for this research",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "displayColumn": {
      "type": "integer",
      "description": "The column to display this research in"
    },
    "displayRow": {
      "type": "integer",
      "description": "The row to display this research in"
    },
    "icon_item": {
      "type": "string",
      "description": "The item icon for this research. Mutually exclusive with icon_research."
    },
    "icon_resource": {
      "type": "string",
      "description": "The resource icon for this research. Mutually exclusive with icon_item."
    },
    "complexity": {
      "type": "integer",
      "description": "The complexity of this research. Used in creating research notes."
    },
    "isSpecial": {
      "type": "boolean",
      "description": "Whether this research is \"special\". Slightly changes the icon of the research. Mutually exclusive with isRound."
    },
    "isSecondary": {
      "type": "boolean",
      "description": "Whether this research is secondary"
    },
    "isRound": {
      "type": "boolean",
      "description": "Whether this research is round. Changes the icon of the research. Mutually exclusive with isSpecial."
    },
    "isStub": {
      "type": "boolean",
      "description": "Whether this research is a stub"
    },
    "isVirtual": {
      "type": "boolean",
      "description": "Whether this research is virtual. This will not be displayed in the Thaumonomicon, but can be used as a parent for other researches"
    },
    "isConcealed": {
      "type": "boolean",
      "description": "Whether this research is concealed until parents are completed."
    },
    "isHidden": {
      "type": "boolean",
      "description": "Whether this research is hidden until parents are completed."
    },
    "isLost": {
      "type": "boolean",
      "description": "Whether this research is \"lost\". Seems to have something to do with Eldritch research"
    },
    "isAutoUnlock": {
      "type": "boolean",
      "description": "Whether this research is auto-unlocked on completion of parents"
    },
    "itemTriggers": {
      "type": "array",
      "description": "The item triggers for this research",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "entityTriggers": {
      "type": "array",
      "description": "The entity triggers for this research",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "aspectTriggers": {
      "type": "array",
      "description": "The aspect triggers for this research",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "pages": {
      "type": "array",
      "description": "The pages for this research",
      "items": {
        "type": "object",
        "properties": {
          "pageType": {
            "type": "string",
            "description": "The type of the page",
            "enum": ["text", "arcane", "recipe", "image", "smelting", "crafting", "infusion"]
          },
          "number": {
            "type": "integer",
            "description": "The page number. Must start at 0 and increase by 1 for each page",
            "minimum": 0,
            "uniqueItems": true
          },
          "text": {
            "type": "string",
            "description": "The text description on the page, if the page type is \"text\" or \"image\""
          },
          "resource": {
            "type": "string",
            "description": "The resource of the image shown on the page, if the page type is \"image\""
          },
          "item": {
            "type": "object",
            "properties": {
              "item": {
                "type": "string",
                "description": "The output of the recipe. Required for page types \"arcane\", \"recipe\", \"smelting\", \"crafting\", and \"infusion\""
              },
              "meta": {
                "type": "integer",
                "description": "The meta of the item",
                "minimum": 0
              },
              "amount": {
                "type": "integer",
                "description": "The amount of the item",
                "minimum": 1
              }
            }
          },
          "aspects": {
            "type": "array",
            "description": "The aspects of the page. Required for page type \"aspect\"",
            "items": {
              "type": "object",
              "properties": {
                "aspect": {
                  "type": "string",
                  "description": "The aspect of the page"
                },
                "amount": {
                  "type": "integer",
                  "description": "The amount of the aspect",
                  "minimum": 1
                }
              }
            },
            "uniqueItems": true
          }
        }
      },
      "dependentSchemas": {

      },
      "minItems": 1
    }
  },
  "required": ["key", "category", "pages", "displayColumn", "displayRow", "tooltip"]
}

=== rndmorris/Salis-Arcana/docs/research/example_research.json
{
  "key": "CAP_gold",
  "category": "THAUMATURGY",
  "name": "Gold Wand Caps",
  "tooltip": "Capping things off with style",
  "aspects": [
    {
      "aspect": "metallum",
      "amount": 3
    },
    {
      "aspect": "lucrum",
      "amount": 3
    },
    {
      "aspect": "instrumentum",
      "amount": 3
    }
  ],
  "parents": [
    "BASICTHAUMATURGY"
  ],
  "siblings": [
    "salisarcana:REPLACEWANDCAPS"
  ],
  "displayColumn": 3,
  "displayRow": 2,
  "icon_item": "Thaumcraft:WandCap:1",
  "icon_resource": "",
  "complexity": 1,
  "isSpecial": false,
  "isSecondary": false,
  "isRound": false,
  "isStub": false,
  "isVirtual": false,
  "isConcealed": false,
  "isHidden": false,
  "isLost": false,
  "isAutoUnlock": false,
  "itemTriggers": [],
  "entityTriggers": [],
  "aspectTriggers": [],
  "pages": [
    {
      "pageType": "text",
      "number": 0,
      "text": "Gold is a far superior focusing agent than iron, and wands capped with this material takes no penalty when used to channel vis.",
      "resource": ""
    },
    {
      "pageType": "arcane",
      "number": 1,
      "text": "",
      "item": {
        "item": "Thaumcraft:WandCap",
        "meta": 1,
        "amount": 1
      },
      "resource": ""
    }
  ]
}
